---
# yamllint disable rule:line-length

sudo: true

addons:
  apt:
    packages:
      - docker-ce
      - python
      - realpath
      - ruby

env:
  global:
    - GO_METALINTER_VERSION="v2.0.11"
    - OPERATOR_SDK_URL="https://github.com/operator-framework/operator-sdk/releases/download/v0.2.0/operator-sdk-v0.2.0-x86_64-linux-gnu"
    - CONTAINER_REPO="johnstrunk/scratcharea"

jobs:
  include:
    - name: Build
      script:
        - docker build -t ${CONTAINER_REPO} -f d1/Dockerfile .
      deploy:
        # Master branch will push the container to :latest
        - provider: script
          script: .travis/push_container.sh ${CONTAINER_REPO} verbatim latest
          on:  # yamllint disable-line rule:truthy
            branch: master
        # Tags of the form v + SEMVER (e.g., v1.2.3) will push to the
        # corresponding container version number (e.g., :1.2.3).
        - provider: script
          script: .travis/push_container.sh ${CONTAINER_REPO} version "$TRAVIS_TAG"
          on:  # yamllint disable-line rule:truthy
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+
